version: '3'

services:
  ApacheServer:                             # SERVER
    image: httpd:latest                         # latest version of Apache HTTP Server image
    container_name: apache-10.9.0.2             # container name for id
    cap_add:                                    # gives the sever all
      - ALL       
    privileged: true                            # privileges(root)
    networks:      
      net-10.9.0.0:                             # network name
        ipv4_address: 10.9.0.2                  # assigns Server's IP
    ports:
      - "80:80"                                 # container's 80 port is server's 80 port (now accessible with 'http://localhost:80')

  Attacker:
    image: ubuntu:latest                        # latest version of Ubuntu image
    container_name: attacker-10.9.0.3           # container name for id
    networks:
      net-10.9.0.0:                             # network name
        ipv4_address: 10.9.0.3                  # assigns Attacker's IP
    command: bash -c "                          
              /etc/init.d/openbsd-inetd start  &&  
              tail -f /dev/null"                # run the attacker constantly
    cap_add:                                    # gives the attacker all
      - ALL
    privileged: true                            # privileges(root)
    volumes:                                    # allows sharing data between host and attacker
      - ./volumes:/volumes

  Monitor:
    image: ubuntu:latest
    container_name: monitor-all
    network_mode: host
    command: bash -c "
              /etc/init.d/openbsd-inetd start  &&
              tail -f /dev/null"
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes:/volumes

networks:
  net-10.9.0.0:
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.0.0/24
