services:
  target:
    build: .
    container_name: target-10.9.0.4
    tty: true
    cap_add:
      - ALL
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - ./volumes:/volumes
      - /tmp/.X11-unix:/tmp/.X11-unix  # Allow access to X server
    networks:
      default:
        ipv4_address: 10.9.0.4
    command: bash -c "/etc/init.d/openbsd-inetd start && ip link set dev eth0 mtu 3000 && tail -f /dev/null"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.0.0/24
