version: '3.8'

services:
  pyshark_sniffer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./volumes:/volumes  # Map the local "volumes" directory directly to "/volumes" in the container
      - /tmp/.X11-unix:/tmp/.X11-unix  # Allow access to the host's X11 display
    environment:
      - DISPLAY=$DISPLAY  # Pass host's DISPLAY variable
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    stdin_open: true  # Keep stdin open for debugging
    tty: true         # Allocate a pseudo-TTY for debugging
